### ISSUE TITLE
Other Types нет типа

### ISSUE THREAD

**Issue by artsoflogic** [WebSystemsSolutions/OpenCart-google-sheets-import-export#5]
Create an OAuth client identifier (select Application Type - Other Types)
Согласно инструкции: должно быть в выборе Other Types, но его нет https://prnt.sc/22ras4j

Web app не работает https://prnt.sc/22rasjt

**Comment by web-systems-solutions** [comment]
Приветствуем! Google сменил API и правила работы с прилоежниемями, вскоре пофиксим и запушим рабочий апдейт! Пока для использования модуля следует выбрать desktop app [https://i.imgur.com/xNsHj3V.png](url)
